apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
 name: m2a-frontend-http
 namespace: m2a-frontend
spec:
 acme:
   email: lucas.saissi@gmail.com
   server: https://acme-v02.api.letsencrypt.org/directory
   privateKeySecretRef:
     # if not existing, it will register a new account and stores it
     name: front-issuer-account-key
   solvers:
     - http01:
         # The ingressClass used to create the necessary ingress routes
         ingress:
           class: traefik