apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: m2a-frontend-ingress
  namespace: m2a-frontend
  annotations:
    cert-manager.io/issuer: "m2a-frontend-http"
spec:
  tls:
    - hosts:
        - m2a.jaipasraisonla.team
      secretName: tls-m2a-front-ingress-http
  rules:
    - host: m2a.jaipasraisonla.team
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: m2a-frontend
                port:
                  name: web